# Generated by Django 3.0.7 on 2020-07-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('incident_description', models.TextField()),
                ('date_of_incident', models.DateField()),
                ('time_of_incident', models.TimeField()),
                ('incident_location', models.TextField(blank=True, null=True)),
                ('initial_severity', models.CharField(max_length=255)),
                ('suspected_cause', models.TextField(blank=True, null=True)),
                ('immediate_actions_taken', models.TextField(blank=True, null=True)),
                ('sub_incident_environmental_incident', models.BooleanField(default=False)),
                ('sub_incident_injury_illness', models.BooleanField(default=False)),
                ('sub_incident_property_damage', models.BooleanField(default=False)),
                ('sub_incident_vehicle', models.BooleanField(default=False)),
                ('reported_by', models.CharField(max_length=255)),
            ],
        ),
    ]
